sudo: false
distro: trusty

language: python

matrix:
  include:
    - python: pypy3.5
    - python: 3.5
    - python: 3.6
    - python: 3.7
      dist: xenial
      sudo: true

install:
  - python -m pip install --upgrade codecov

script:
  - python -m doctest README.md
  - python setup.py test

after_success:
  - codecov
