version: '3'

services:
  paradigm-cpython:
    build:
      context: .
      args:
      - PYTHON_IMAGE=${CPYTHON_IMAGE_NAME}
      - PYTHON_IMAGE_VERSION=${CPYTHON_IMAGE_VERSION}
    image: lycantropos/paradigm-cpython:0.5.0-alpha
    volumes:
      - ./paradigm/:/opt/paradigm/paradigm/
      - ./tests/:/opt/paradigm/tests/
      - ./README.md:/opt/paradigm/README.md
      - ./requirements.txt:/opt/paradigm/requirements.txt
      - ./requirements-tests.txt:/opt/paradigm/requirements-tests.txt
      - ./setup.py:/opt/paradigm/setup.py
      - ./setup.cfg:/opt/paradigm/setup.cfg
    entrypoint: pytest
