version: '3'

services:
  paradigm-cpython:
    build:
      context: .
      args:
        - IMAGE_NAME=${CPYTHON_IMAGE_NAME}
        - IMAGE_VERSION=${CPYTHON_IMAGE_VERSION}
    image: lycantropos/paradigm-cpython:1.0.0
    volumes:
      - ./paradigm:/opt/paradigm/paradigm
      - ./pytest.ini:/opt/paradigm/pytest.ini
      - ./README.md:/opt/paradigm/README.md
      - ./requirements-tests.txt:/opt/paradigm/requirements-tests.txt
      - ./requirements.txt:/opt/paradigm/requirements.txt
      - ./setup.py:/opt/paradigm/setup.py
      - ./tests:/opt/paradigm/tests
    entrypoint: pytest
