version: '3'

services:
  paradigm-cpython:
    build:
      context: .
      args:
        - IMAGE_NAME=${CPYTHON_IMAGE_NAME}
        - IMAGE_VERSION=${CPYTHON_IMAGE_VERSION}
    image: lycantropos/paradigm-cpython:4.1.0
    volumes:
      - ./paradigm:/opt/paradigm/paradigm
      - ./pyproject.toml:/opt/paradigm/pyproject.toml
      - ./README.md:/opt/paradigm/README.md
      - ./setup.py:/opt/paradigm/setup.py
      - ./tests:/opt/paradigm/tests
    entrypoint: pytest
