version: '3'

services:
  paradigm:
    build:
      context: .
      args:
        - IMAGE_NAME=${IMAGE_NAME}
        - IMAGE_VERSION=${IMAGE_VERSION}
    image: lycantropos/paradigm:4.4.0-alpha
    volumes:
      - ./paradigm:/opt/paradigm/paradigm
      - ./pyproject.toml:/opt/paradigm/pyproject.toml
      - ./README.md:/opt/paradigm/README.md
      - ./setup.py:/opt/paradigm/setup.py
      - ./tests:/opt/paradigm/tests
    entrypoint: pytest
