name: CI

on:
  push:
    branches:
      - 'master'
    tags: [ 'v*' ]
  pull_request:
    branches:
      - 'master'
  schedule:
    - cron: '0 0 * * *'

defaults:
  run:
    shell: bash

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v5
      - name: 'Setup Python'
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - name: 'Check Python metadata'
        run: |
          PROJECT_DESCRIPTION=$(python -c 'import json, pathlib, tomllib; print(json.dumps(tomllib.loads(pathlib.Path("pyproject.toml").read_text())))' | jq --raw-output '.project.description')
          MODULE_DOCSTRING=$(python -c "import ${REPOSITORY_NAME//-/_} as module; assert module.__doc__ is not None; print(module.__doc__)")
          if [[ $PROJECT_DESCRIPTION != "$MODULE_DOCSTRING" ]]; then
            echo "Project description should be equal to module docstring, but found \"$PROJECT_DESCRIPTION\" != \"$MODULE_DOCSTRING\".";
            exit 1;
          fi
        env:
          REPOSITORY_NAME: ${{ github.event.repository.name }}
      - name: 'Install pre-commit'
        run: python -m pip install -U pre-commit
      - name: 'Run pre-commit'
        run: pre-commit run --all-files --hook-stage manual

  test:
    name: 'Test'
    runs-on: ${{ matrix.platform.os }}
    strategy:
      fail-fast: false
      matrix:
        python_version: [ '3.10', '3.11', '3.12', '3.13' ]
        platform: [
          { os: 'macos-latest', python_architecture: 'x64' },
          { os: 'ubuntu-latest', python_architecture: 'x64' },
          { os: 'windows-latest', python_architecture: 'x64' },
          { os: 'windows-latest', python_architecture: 'x86' },
        ]
        exclude:
          - python_version: '3.10'
            platform: { os: 'macos-latest', python_architecture: 'x64' }
        include:
          - python_version: '3.10'
            platform: { os: 'macos-13', python_architecture: 'x64' }
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v5
      - name: 'Setup Python'
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python_version }}
          architecture: ${{ matrix.platform.python_architecture }}
      - name: 'Install packaging tools'
        run: python -m pip install -U pip setuptools wheel
      - name: 'Install coverage dependencies'
        run: python -m pip install -U coverage[toml]
      - name: 'Install in editable mode'
        run: python -m pip -v install -e '.[tests]'
      - name: 'Run doctests'
        run: |
          coverage run -m doctest README.md
          coverage run --append -m pytest --doctest-modules --ignore=tests
      - name: 'Run tests'
        run: coverage run --append -m pytest
      - name: 'Collect coverage'
        run: coverage combine && coverage xml
      - name: 'Upload coverage'
        uses: codecov/codecov-action@v5
        with:
          fail_ci_if_error: false
          token: ${{ secrets.CODECOV_TOKEN }}
        continue-on-error: true

  pre-deploy:
    name: 'Pre-deploy'
    runs-on: ubuntu-latest
    needs: test
    if:
      github.event_name == 'push' && github.ref_type == 'tag'
      || github.actor == 'dependabot[bot]'
    steps:
      - name: '_'
        run: echo "Pre-deploy step"

  build:
    name: 'Build'
    runs-on: ubuntu-latest
    needs: pre-deploy
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v5
      - name: 'Setup Python'
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - name: 'Install packaging tools'
        run: python -m pip install -U build
      - name: 'Build'
        run: python -m build --sdist --wheel
      - name: 'Upload'
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist

  test-distributions:
    name: 'Test distributions'
    runs-on: ${{ matrix.platform.os }}
    needs: build
    strategy:
      matrix:
        python_version: [ '3.10', '3.11', '3.12', '3.13' ]
        platform: [
          { os: 'macos-latest', python_architecture: 'x64' },
          { os: 'ubuntu-latest', python_architecture: 'x64' },
          { os: 'windows-latest', python_architecture: 'x64' },
          { os: 'windows-latest', python_architecture: 'x86' },
        ]
        exclude:
          - python_version: '3.10'
            platform: { os: 'macos-latest', python_architecture: 'x64' }
        include:
          - python_version: '3.10'
            platform: { os: 'macos-13', python_architecture: 'x64' }
    steps:
      - name: 'Setup Python'
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python_version }}
          architecture: ${{ matrix.platform.python_architecture }}
      - name: 'Download distributions'
        uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist
      - name: 'Install from distributions'
        run: >
          python -m pip install --find-links=dist --no-deps
          "${REPOSITORY_NAME//-/_}"
        env:
          REPOSITORY_NAME: ${{ github.event.repository.name }}

  deploy:
    name: 'Deploy'
    environment: release
    needs: test-distributions
    runs-on: ubuntu-latest
    steps:
      - name: 'Download distributions'
        uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist
      - name: 'Upload to Test PyPI'
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: dist
          password: ${{ secrets.TEST_PYPI_API_TOKEN }}
          repository-url: https://test.pypi.org/legacy/
          skip-existing: ${{ github.actor == 'dependabot[bot]' }}
        continue-on-error: true
      - name: 'Upload to PyPI'
        if: github.actor != 'dependabot[bot]'
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: dist
          password: ${{ secrets.PYPI_API_TOKEN }}
